
services:
  # 1. 数据库服务
  db:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    image: ${MYSQL_CONTAINER_NAME}:latest # <--- 显式指定镜像名
    container_name: ${MYSQL_CONTAINER_NAME}
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - ylf-network
    ports:
      - "${MYSQL_PORT}:${MYSQL_INTERNAL_PORT}"

  # 2. 后端服务 (Django)
  backend:
    build:
      context: ./UniDjango
    image: ${BACKEND_CONTAINER_NAME}:latest # <--- 显式指定镜像名
    container_name: ${BACKEND_CONTAINER_NAME}
    restart: always
    environment:
      DB_HOST: ${MYSQL_CONTAINER_NAME}
      DEBUG: "False"
    volumes:
      - ./UniDjango/media:/app/media
    depends_on:
      - db
    networks:
      - ylf-network
    ports:
      - "${BACKEND_PORT}:${BACKEND_INTERNAL_PORT}"

  # 3. 前端服务 (Vue + Nginx) - 生产环境模式
  frontend:
    build:
      context: ./frontend  # <--- 注意这里改成了相对路径
    image: ${FRONTEND_CONTAINER_NAME}:latest # <--- 显式指定镜像名
    container_name: ${FRONTEND_CONTAINER_NAME}
    restart: always
    ports:
      # - "80:80" # 开发模式下注释掉，避免端口冲突
      - "${FRONTEND_PORT}:${FRONTEND_INTERNAL_PORT}" # 映射到其他端口
    depends_on:
      - backend
    networks:
      - ylf-network

networks:
  ylf-network:
    driver: bridge
